### PR TITLE
Introduce a new HasScopedToken class to enforce scopes

### PR DESCRIPTION
**Pull request by mettursathish**
Introduce a new HasScopedToken class to enforce scopes for JWT

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @mettursathish! I've created [OSPR-2440](https://openedx.atlassian.net/browse/OSPR-2440) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-drf-extensions/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by douglashall** [comment]
Hi @mettursathish! I'm still somewhat unclear on why this permission class is needed and we can't just use DOT's [TokenHasScope](https://github.com/jazzband/django-oauth-toolkit/blob/master/oauth2_provider/contrib/rest_framework/permissions.py#L16) permission class. It may become clear to menas I work through the edx-platform PR.

**Comment by mettursathish** [comment]
@douglashall Sure, please discuss and keep us posted.

**Comment by douglashall** [comment]
@mettursathish Closing this in favor of the already merged https://github.com/edx/edx-drf-extensions/pull/28.

**Comment by edx-webhook** [comment]
@mettursathish Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-drf-extensions&entry.867055334=https://github.com/edx/edx-drf-extensions/pull/27&entry.1484655318=https://github.com/mettursathish&entry.752974735=2018-05-25+22:09&entry.1917517419=2018-06-19+20:14&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
